# This is a generated file. Not intended for manual editing.
version: "3.8"
services:
  rest-server:
    build:
      context: "/Users/stefanrezk/Documents/GitHub/DMS/RestAPITeamE/RestAPITeamE"
      dockerfile: "Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/RestAPITeamE.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "restapiteame:dev"
    ports: []
    volumes:
    - "/Users/stefanrezk/.nuget/packages:/home/app/.nuget/packages"
    - "/Users/stefanrezk/Documents/GitHub/DMS/RestAPITeamE/RestAPITeamE:/app:rw"
    - "/Users/stefanrezk/Documents/GitHub/DMS/RestAPITeamE:/src:rw"
    working_dir: "/app"
